### ISSUE TITLE
It runs forver for resizing image

### ISSUE THREAD

**Issue by jinghui612** [meso-unimpressed/deep_zoom_slicer#2]
Hi all,
    I got a problem, I dont know how I can fix it up.
    The problem is that I use deep_zoom_slicer to tile one very big jpg image. 
    size: 110.3MB  
    Dimensions: 42240 x 56960
    The problem is that, each time it finish the slicer for level  16 then it starts to resizing. Then it runs forever. I run it up to 24 hours, it stills do the resizing only for level 16. I try to use small images, it works. However, it just cannot work for the big image.

```
 My computer is Mac book. I use 
 ImageMagick 6.6.1-0   
 ruby 1.8.7

Thank you very much~
```

Johnny

**Comment by hanssen** [comment]
I'll have a look soon. Thanks for the report!

**Comment by ccoenen** [comment]
We were having a very similar issue, too. So far, this seems to be related to ImageMagick or RMagick, we were not able to resize an image that size with a simple three-line program either.

I don't believe, we can fix it for deep_zoom_slicer on our own.

**Comment by jinghui612** [comment]
ok thanx. I found a way which looks like a solution.  We can resize the images before stitching them to the final big one. Then we can stitch the resized images for the previous level --- 15.
We assume the max level for the big picture is 16. Then skip the resize process bwtween 16 to 15. Using the image for 15 then do the stitching. 
My English is not very good. I hope you can understand it.
I also found that the width 13200 hight 17800 can be resized. This is doable.

I hope this can give you some help.

Cheers
Johnny
